// <auto-generated />
using HelloEF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace HelloEF.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("HelloEF.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breed");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("OwnerId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<double>("Weight");

                    b.HasKey("DogId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("HelloEF.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DOB");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("HelloEF.Models.Walk", b =>
                {
                    b.Property<int>("WalkId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DogId");

                    b.Property<int>("Duration");

                    b.Property<int>("OwnerId");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("WalkId");

                    b.HasIndex("DogId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("HelloEF.Models.Dog", b =>
                {
                    b.HasOne("HelloEF.Models.Owner", "Owner")
                        .WithMany("Dogs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HelloEF.Models.Walk", b =>
                {
                    b.HasOne("HelloEF.Models.Dog", "WalkedDog")
                        .WithMany("WalksTaken")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HelloEF.Models.Owner", "Walker")
                        .WithMany("WalksTaken")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
